### ISSUE TITLE
Markup won’t get generated on page load

### ISSUE THREAD

**Issue by nagisa** [ligthyear/clippy-service#12]
On page load markup won’t get generated even though the fields may be filled-in.

Reproduce by:
1. Going to the website;
2. Entering some data into username/repo fields (observe markup appearing);
3. Reloading the page (observe fields staying filled but no markup).

**Comment by gnunicorn** [comment]
The reload-prefill is a browser feature, not something we have implemented ourselfes. Looks like the browser isn't triggering the on-change-fields (or we aren't picking up on it right). May I ask which browser and OS you are using to test this?
