### ISSUE TITLE
Flat badge style is equivalent to plastic (does not work?)

### ISSUE THREAD

**Issue by nagisa** [ligthyear/clippy-service#13]
Flat style badge looks the same as the plastic style badge.

**Comment by gnunicorn** [comment]
It works here, the difference just isn't thaaaat obvious – there is a little gradient over the "plastic" version, which I suppose should give it the impression of a button or something:

![screen shot 2016-03-05 at 13 16 18](https://cloud.githubusercontent.com/assets/40496/13546070/ad758702-e2d4-11e5-8beb-eda3f847fafd.png)
![screen shot 2016-03-05 at 13 16 32](https://cloud.githubusercontent.com/assets/40496/13546071/ad75f4ee-e2d4-11e5-84b9-7dea855a452f.png)

Please reopen if this isn't properly updating for you!
