### ISSUE TITLE
Broken on Github Readme

### ISSUE THREAD

**Issue by Manishearth** [ligthyear/clippy-service#16]
https://www.reddit.com/r/rust/comments/4929fw/clippy_linting_as_a_service/d0ogo23?context=3

**Comment by Manishearth** [comment]
Also, @ligthyear, clippy.bashy.io is down?

**Comment by gnunicorn** [comment]
I don't think the cache control header is the problem – it doesn't make sense as we are just redirecting to shields.io anyways and they do have a cache control header. I think the redirect might actually be the problem. Github caches the badges when rendering the README, which means they are downloaded first – and I am afraid github doesn't follow the redirects..

**Comment by gnunicorn** [comment]
Not 100% sure which one of them actually fixed it – thought I didn't see any changes until after I changed the 301 Redirect – BUT it works now. Rebuilding right now (thought the exact version is already deployed :) )

**Comment by skade** [comment]
Still stuck in the state "linting" for me. https://github.com/skade/html_safe_buffer

**Comment by gnunicorn** [comment]
@skade could try to refresh the GitHub cached version? Just push a new
revision to that file (just add a `?` in the URL or so). Does that fix it?

---

Weird though, as prior it would cause no rendering to happen at all. I am
afraid that GitHub might ignore the expiration of our redirects and caches
only the last result - and shields.io report static badges with "never
expire". Might have to render our own badges after all..

**Comment by Manishearth** [comment]
It works now
