### ISSUE TITLE
Badges seems to be cached and isn't updating

### ISSUE THREAD

**Issue by dten** [ligthyear/clippy-service#34]
https://github.com/dten/computus

My badge currently says 11 clippy warnings, but clicking the link says none. also going directly to the image says Success.

https://clippy.bashy.io/github/dten/computus/master/badge.svg

This issue from shields says headers need setting so that github does not cache the images so aggressively
https://github.com/badges/shields/issues/221

**Comment by gnunicorn** [comment]
Hello @dten and thanks for the report.

At the moment we are just forwarding to shields so their caching will be used by Github and the ticket you've linked against is already closed as fixed. However, just a quick look makes me believe they are sending an "Expire" header for 24h for static badges (which we are using). Which makes me believe Github will reevaluate the URL every 24h and figure out, it should show the other one. Could you confirm (tomorrow) that it indeed did update?

Not exactly sure what else we can other than provide our own badge rendering (as discussed in #14 ).

**Comment by dten** [comment]
Hi it's been just over 24hrs since I made it and it has updated now. Guess that'll have to do :) :+1:
