### ISSUE TITLE
Travis build broken

### ISSUE THREAD

**Issue by durka** [ligthyear/clippy-service#46]
The Travis build is not running, so even if clippy's Travis build correctly triggers a clippy-service rebuild (see https://github.com/Manishearth/rust-clippy/pull/1369), it won't work.

**Comment by gnunicorn** [comment]
Indeed. I did the one thing that is never expected to happen: move repositories. I fixed the links and the the build is kinda working correctly again. Just waiting for clippy to work on nightly again to confirm it all goes through.
