### ISSUE TITLE
Certificate seems to have expired

### ISSUE THREAD

**Issue by hawkw** [ligthyear/clippy-service#47]
Attempting to load [clippy.bashy.io](https://clippy.bashy.io) using HTTPS results in the browser displaying a warning that the site's certificate has expired. 

See attached screenshot:
<img width="539" alt="screen shot 2017-01-01 at 10 37 09 am" src="https://cloud.githubusercontent.com/assets/2796466/21581808/d9beeb00-d00e-11e6-9034-25ec098b4d3d.png">

**Comment by gnunicorn** [comment]
That is correct. I have to investigate what is going on, it keeps happening with the encrypt-everywhere setup we have :( ... Need so fix it once and for all...

**Comment by buntine** [comment]
Hey, just so you know, this is still happening and thus all of the generated github "badges" are not rendering. I'm removing this badge from my project for now, but would love to see this get fixed.

**Comment by gnunicorn** [comment]
So. Auto-renew is set up, but the system reguarly runs out of disk space and can't run it. I've run it now, but it might happen again. I need to restart this entire setup with a more recent version of docker and dokku ... just not having the time right now :( .

Please reopen if the issue failed again and I'll run the command manually ... until then. Closing as fixed.
